version: "3.9"

services:
  tgbot:
    image: capy-cloud-bot.tgbot:latest
    container_name: capy-cloud-bot.tgbot
    restart: unless-stopped
    env_file:
      - ".env"
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - capy-cloud-bot.postgres.network
    volumes:
      - capy-cloud-bot.tgbot.data:/usr/src/app/${UPLOAD_DIR}:rw

  postgres:
    container_name: capy-cloud-bot.postgres
    image: "postgres:15-alpine"
    hostname: capy-cloud-bot.postgres
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    networks:
      - capy-cloud-bot.postgres.network
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: ${POSTGRES_USER:-$USER}
      POSTGRES_DB: ${POSTGRES_DB:-${POSTGRES_USER:-$USER}}
    volumes:
      - capy-cloud-bot.postgres.data:/var/lib/postgresql/users:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  capy-cloud-bot.tgbot.data: {}
  capy-cloud-bot.postgres.data: {}

networks:
  capy-cloud-bot.postgres.network: {}
